coverage:
  ignore:
    - "packages/relayer/bindings/**/*"
    - "packages/relayer/mock/**/*"
    - "packages/relayer/cmd/**/*"
  status:
    project: off
    patch: off

flag_management:
  default_rules:
    carryforward: true
  individual_flags:
    - name: protocol
      paths:
        - packages/protocol/**/*
    - name: relayer
      paths:
        - packages/relayer/**/*

comment:
  show_carryforward_flags: true
