version: "3.8"
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=relayer
      - MYSQL_ROOT_PASSWORD=passw00d
    ports:
      - "3306:3306"
    volumes:
      - ~/.docker-conf/mysql/data/:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
volumes:
  db:
    driver: local
networks:
  rabbitmq_go_net:
    driver: bridge
