global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "rabbitmq"
    static_configs:
      - targets: ["host.docker.internal:15692"]

  - job_name: "rabbitmq_queue"
    metrics_path: /metrics/per-object
    static_configs:
      - targets: ["host.docker.internal:15692"]
