version: "3.9"

services:
  geth:
    image: ethereum/client-go:v1.13.14
    restart: unless-stopped
    volumes:
      - ../../deployments:/data
      - .:/host
    ports:
      - 18545:8545
    entrypoint: "/host/init_geth.sh"
