# See more config options https://github.com/foundry-rs/foundry/tree/master/config
[profile.default]
solc-version = "0.8.20"
src = 'contracts'
out = 'out'
test = 'test'
libs = ['lib']
gas_price = 10000000000            # gas price is 10 Gwei
optimizer = true
optimizer_runs = 200
ffi = true
gas_limit = '18446744073709551615'
memory_limit = 2073741824

# Do not change the block_gas_limit value, TaikoL2.t.sol depends on it.
block_gas_limit = 30000000 #30M
# For mainnet_mock tokenomics test we need a huge value to run lots of iterations.
# Use the above 30M for TaikoL2.t.sol related tests, only use this number with mainnet simulation.
#block_gas_limit = 3000000000 #3000M


fs_permissions = [
  { access = "read", path = "./out" },
  { access = "read-write", path = "./deployments" },
  { access = "read", path = "./test" },
]

fuzz = { runs = 256 }

[fmt]
bracket_spacing = true
line_length = 80
multiline_func_header = 'all'
number_underscore = 'thousands'
wrap_comments = true
