name: Feature request 💡
description: Request a feature
title: "feat: INSERT_DESCRIPTIVE_TITLE"
labels: ["feat", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Before submitting, please check if an existing issue already exists. Thanks for taking the time to improve Taiko!
  - type: textarea
    id: description
    attributes:
      label: Describe the feature request
      description: A concise description of what the problem and proposed solution is.
      value: Description of the feature request here.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A concise description of any alternative solutions you've considered.
      value: Description of the alternatives you've considered here.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Provide any additional context, screenshots, etc.
      value: Additional context here.
