# See: https://golangci-lint.run/usage/configuration/
#
# Note: for VSCode, you must have the following settings to use this configuration:
#
# "go.lintTool": "golangci-lint",
# "go.lintFlags": [
#   "--fast",
#   "--config=${workspaceFolder}/.golangci.yml"
# ],

output:
  format: colored-line-number

linters:
  enable:
    - errcheck
    - funlen
    - gocognit
    - gocritic
    - gofmt
    - golint
    - gosec
    - gosimple
    - lll
    - unused
    - whitespace
    - wsl

linters-settings:
  funlen:
    lines: 137
    statements: 54
  gocognit:
    min-complexity: 43
  lll:
    line-length: 140

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - funlen
    - path: contracts\.go
      linters:
        - lll

