name: Bridge UI CI/CD

on:
  push:
    branches-ignore:
      - release-please-*
    paths:
      - "packages/bridge-ui/**"
  pull_request:
    paths:
      - "packages/bridge-ui/**"

jobs:
  build-and-test:
    uses: ./.github/workflows/bridge-ui-ci.yml

  # Deployment name follow the pattern: deploy_<appname(bridge-ui)>_<network(devnet|hekla|mainnet)>_<environment(preview|production)>
  deploy_bridge-ui_hekla_preview:
    if: ${{ github.ref_name != 'main' }}
    needs: build-and-test
    uses: ./.github/workflows/vercel-deploy.yml
    with:
          environment: 'preview'
          flags: ''
    secrets:
      vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID_BRIDGE_UI_HEKLA }}
      vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
      vercel_token: ${{ secrets.VERCEL_TOKEN }}

  deploy_bridge-ui_devnet_preview:
    if: ${{ github.ref_name != 'main' }}
    needs: build-and-test
    uses: ./.github/workflows/vercel-deploy.yml
    with:
          environment: 'preview'
          flags: ''
    secrets:
      vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID_BRIDGE_UI_INTERNAL }}
      vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
      vercel_token: ${{ secrets.VERCEL_TOKEN }}

  deploy_bridge-ui_hekla_production:
    if: ${{ github.ref_name == 'main' && contains(github.ref, 'refs/tags/bridge-ui-') }}
    needs: build-and-test
    uses: ./.github/workflows/vercel-deploy.yml
    with:
      environment: 'production'
      flags: '--prod'
    secrets:
      vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID_BRIDGE_UI_HEKLA }}
      vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
      vercel_token: ${{ secrets.VERCEL_TOKEN }}
