name: Vercel Preview Deployment

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on:
  push:
    branches-ignore:
      - main
      - release-please-*
    paths:
      - "packages/bridge-ui/**"

jobs:
  Deploy-Preview:
    runs-on: [taiko-runner]
    strategy:
      matrix:
        include:
          - project: "Public"
            org_id: ${{ secrets.VERCEL_ORG_ID}}
            project_id: ${{ secrets.VERCEL_PROJECT_ID_BRIDGE_UI}}
          - project: "Internal"
            org_id: ${{ secrets.VERCEL_ORG_ID }}
            project_id: ${{ secrets.VERCEL_PROJECT_ID_BRIDGE_UI_INTERNAL}}
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Setup Vercel Environment for ${{ matrix.project }}
        run: |
          vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ matrix.org_id }} --project-id=${{ matrix.project_id }}
          vercel link --token=${{ secrets.VERCEL_TOKEN }} --confirm --name=${{ matrix.project }} --scope=${{ matrix.org_id }}
      - name: Build Project Artifacts for ${{ matrix.project }}
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel for ${{ matrix.project }}
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
