name: Golang

on:
  push:
    branches: [main]
    paths:
      - "packages/relayer/**"
  pull_request:
    paths:
      - "packages/relayer/**"

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest

          # Optional: working directory, useful for monorepos
          working-directory: ./packages/relayer
          args: --config=.golangci.yml

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.0"

      - name: relayer - Unit Tests
        working-directory: ./packages/relayer
        run: go test ./... -count=1
