name: Guardian UI CI/CD

on:
  push:
    branches-ignore:
      - release-please-*
    paths:
      - "packages/guardian-prover-health-check-ui/**"

jobs:
  # Deployment name follow the pattern: deploy_<appname(bridge-ui)>_<network(devnet|hekla|mainnet)>_<environment(preview|production)>
  deploy_guardian-ui_hekla_preview:
    if: ${{ !github.ref_name == 'main' }}
    uses: ./.github/workflows/guardian-ui-deploy.yml
    with:
      environment: "preview"
      flags: ""
      vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
      vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID_GUARDIAN_PROVER_HEALTH_CHECK_UI_HEKLA }}

  deploy_guardian-ui_devnet_preview:
    if: ${{ !github.ref_name == 'main' }}
    uses: ./.github/workflows/guardian-ui-deploy.yml
    with:
      environment: "preview"
      flags: ""
      vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
      vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID_GUARDIAN_PROVER_HEALTH_CHECK_UI_INTERNAL }}

  deploy_guardian-ui_hekla_production:
    if: ${{ github.ref_name == 'main' && startsWith(github.ref, 'refs/tags/guardian-prover-health-check-ui-') }}
    uses: ./.github/workflows/guardian-ui-deploy.yml
    with:
      environment: "production"
      flags: "--prod"
      vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
      vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID_GUARDIAN_PROVER_HEALTH_CHECK_UI_HEKLA }}
