name: "Lint PR"

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          scopes: |
            branding
            bridge-ui
            protocol
            relayer
            status-page
            tokenomics
            website
            whitepaper
