name: Lint PR

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          scopes: |
            repo
            branding
            bridge-ui-v2
            deps
            eventindexer
            fork-diff
            protocol
            relayer
            starter-dapp
            status-page
            tokenomics
            website
            whitepaper
            deps-dev
          requireScope: true
