name: Protocol

on:
  push:
    branches: [main]
    paths:
      - "packages/protocol/**"
  pull_request:
    paths:
      - "packages/protocol/**"

jobs:
  build:
    runs-on: [taiko-runner]
    permissions:
      # Give the necessary permissions for stefanzweifel/git-auto-commit-action.
      contents: write
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-2cb875799419c907cc3709e586ece2559e6b340e

      - name: Install pnpm dependencies
        uses: ./.github/actions/install-pnpm-dependencies

      - name: Check formatting
        working-directory: ./packages/protocol
        run: forge fmt --check

      - name: Unit tests
        working-directory: ./packages/protocol
        run: pnpm clean && pnpm test

      - name: Generate contract layout table
        working-directory: ./packages/protocol
        run: pnpm layout

      - name: Commit contract layout table
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add contract layout table"

      - name: Generate genesis
        working-directory: ./packages/protocol
        run: pnpm test:genesis

      - name: Run snapshot (Foundry)
        working-directory: ./packages/protocol
        run: pnpm snapshot

      - name: Deploy L1 contracts
        working-directory: ./packages/protocol
        run: |
          anvil --hardfork cancun &
          while ! nc -z localhost 8545; do
            sleep 1
          done
          pnpm test:deploy
