name: Protocol

on:
  push:
    branches: [main]
    paths:
      - "packages/protocol/**"
  pull_request:
    paths:
      - "packages/protocol/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install pnpm dependencies
        uses: ./.github/actions/install-pnpm-dependencies

      - name: protocol - Unit Tests
        working-directory: ./packages/protocol
        run: pnpm clean && pnpm compile:hardhat && pnpm test

      - name: protocol - Generate Genesis
        working-directory: ./packages/protocol
        run: pnpm test:genesis

      # TODO: CompilerError: Stack too deep
      # - name: protocol - Test Coverage
      #   working-directory: ./packages/protocol
      #   run: pnpm test:coverage

      - name: protocol - Run snapshot (foundry)
        working-directory: ./packages/protocol
        run: pnpm snapshot

      - name: protocol - Deploy L1 Contracts
        working-directory: ./packages/protocol
        run: |
          anvil &
          while ! nc -z localhost 8545; do
            sleep 1
          done
          pnpm deploy:foundry

      # - name: protocol - Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     directory: ./packages/protocol/coverage
      #     flags: protocol

      # - name: protocol - Generate contract documentation
      #   run: pnpm -F protocol export:docs

      # - name: protocol - Commit contract documentation
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: Add auto-generated contract documentation
      #     file_pattern: "**/*.md"
