name: Snaefell UI CI/CD

on:
  push:
    tags:
      - "snaefull-ui-v*"
  pull_request:
    paths:
      - "packages/snaefell-ui/**"

jobs:
  build-and-test:
    uses: ./.github/workflows/snaefell-ui--ci.yml

  # Deployment name follow the pattern: deploy_<appname(snaefell-ui)>_<network(devnet|hekla|mainnet)>_<environment(preview|production)>
  deploy_snaefell-ui_mainnet_preview:
    if: ${{ github.ref_name != 'main' }}
    needs: build-and-test
    uses: ./.github/workflows/repo--vercel-deploy.yml
    with:
      environment: "preview"
      flags: ""
    secrets:
      vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID_SNAEFELL_UI_MAINNET }}
      vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
      vercel_token: ${{ secrets.VERCEL_TOKEN }}

  deploy_snaefell-ui_mainnet_production:
    if: ${{ startsWith(github.ref, 'refs/tags/snaefull-ui-v') }}
    needs: build-and-test
    uses: ./.github/workflows/repo--vercel-deploy.yml
    with:
      environment: "production"
      flags: "--prod"
    secrets:
      vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID_SNAEFELL_UI_MAINNET }}
      vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
      vercel_token: ${{ secrets.VERCEL_TOKEN }}
