name: "CI"

on:
  push:
    branches: [main]
    paths:
      - "packages/taiko-client/**"
  pull_request:
    paths:
      - "packages/taiko-client/**"
      - "go.mod"
      - "go.sum"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
          cache: true

      - name: Lint
        working-directory: packages/taiko-client
        run: make lint

  integration_tests:
    name: Integration tests
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
          cache: true

      - name: Install pnpm dependencies
        uses: ./.github/actions/install-pnpm-dependencies

      - name: Test
        working-directory: packages/taiko-client
        run: make test

      - name: Codecov.io
        uses: codecov/codecov-action@v3
        with:
          files: packages/taiko-client/coverage.out
