name: Taikoon UI CI/CD

on:
  push:
    branches-ignore:
      - release-please-*
    paths:
      - "packages/taikoon-ui/**"
  pull_request:
    paths:
      - "packages/taikoon-ui/**"

jobs:
  build-and-test:
    uses: ./.github/workflows/taikoon-ui-ci.yml

  # Deployment name follow the pattern: deploy_<appname(taikoon-ui)>_<network(devnet|hekla|mainnet)>_<environment(preview|production)>
  deploy_taikoon-ui_mainnet_preview:
    if: ${{ github.ref_name != 'main' }}
    needs: build-and-test
    uses: ./.github/workflows/vercel-deploy.yml
    with:
          environment: 'preview'
          flags: ''
    secrets:
      vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID_TAIKOON_UI_MAINNET }}
      vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
      vercel_token: ${{ secrets.VERCEL_TOKEN }}

  deploy_taikoon-ui_mainnet_production:
    if: ${{ github.ref_name == 'main' && contains(github.ref, 'refs/tags/taikoon-ui-') }}
    needs: build-and-test
    uses: ./.github/workflows/vercel-deploy.yml
    with:
      environment: 'production'
      flags: '--prod'
    secrets:
      vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID_TAIKOON_UI_MAINNET }}
      vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
      vercel_token: ${{ secrets.VERCEL_TOKEN }}
