name: Taikoon UI

on:
  push:
    branches: [main]
    paths:
      - "packages/taikoon-ui/**"
  pull_request:
    paths:
      - "packages/taikoon-ui/**"

jobs:
  build:
    runs-on: [taiko-runner]
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install pnpm dependencies
        uses: ./.github/actions/install-pnpm-dependencies

      - name: Check formatting
        working-directory: ./packages/taikoon-ui
        run: pnpm lint

      - name: Frontend build
        working-directory: ./packages/taikoon-ui
        run: |
          export PUBLIC_WALLETCONNECT_PROJECT_ID="fake_project_id"
          export PUBLIC_IPFS_GATEWAY="https://ipfs.io/ipfs/"
          pnpm build
